### ISSUE TITLE
Some kind of blocking/return issue.

### ISSUE THREAD

**Issue by paulstraw** [subtleGradient/node-photoshop#2]
I'm having a weird issue where Photoshop doesn't seem to want to return anything unless I do something blocking first. Here's some sample code:

``` javascript
var photoshop = require('photoshop');

function recentFilesThatExist_jsx(){
	var files = app.recentFiles,
		fileList = files.map(File).filter(function(file){return file.exists});

	alert(fileList);

	return fileList;
}

photoshop.invoke(recentFilesThatExist_jsx, function(err, recentFiles) {
	console.log(recentFiles);
});
```

That works as expected, but if I comment out the `alert(fileList);` part, nothing gets returned. Any idea what could be causing that? (Running Node 0.10.5 and Photoshop CS6).

EDIT: This is inside node-webkit. Oddly, the same code works fine if I just run it directly from a Node REPL. Very strange.

**Comment by subtleGradient** [comment]
Hello from the distant future.
I guess my past self never got around to fixing this.
Looks like the workaround is to use streams then I guess

**Comment by paulstraw** [comment]
Hah! ¯\_(ツ)_/¯
