### ISSUE TITLE
After Effects execution - node does not exit

### ISSUE THREAD

**Issue by fabiantheblind** [subtleGradient/node-photoshop#3]
Hi there,  
awesome module. Thanks. I tried to execute your example and ran into an error.  

It sends the script to AE und the alert shows up. When I hit the "ok" button I can return to the terminal but node is stuck there. It does not exit.  
Take a look at the screenshot if it is unclear what I mean.  
![stuck-screen](https://cloud.githubusercontent.com/assets/315106/3775528/942569c4-1946-11e4-9473-f342d908c081.png)

Am I doing something wrong?  

node: 0.10.29  
npm: 1.4.21  
photoshop module: 0.5.0  
OS: Mac OSX 10.9.4  
AE CC 2014: 13.0.0.214  

My index.js taken from your examples:  

    require('photoshop/aftereffects').createStream(function jsx(stream, props){
      stream.writeln(JSON.stringify(props));
      alert("After Effects won't return until this window is closed, but the stream already sent its data!");
    }, [{lulz:true}])
    .pipe(process.stdout);

**Comment by subtleGradient** [comment]
I figured it out! Add this to your jsx code:

    stream.close();

That'll tell After Effects to disconnect from the stream which will allow node.js to close

**Comment by fabiantheblind** [comment]
cool. Closing old issues? :+1: I just can't remember what I was doing.
